spring:
  datasource:
    hikari:
      #自动提交
      auto-commit: true
      connection-test-query: SELECT 1
      #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒 -->
      connection-timeout: 30000
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟 -->
      idle-timeout: 600000
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，
      #建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->
      max-lifetime: 620000
      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count) -->
      maximum-pool-size: 30
      #池中维护的最小空闲连接数
      minimum-idle: 5
      pool-name: DatebookHikariCP
      read-only: false
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///mctpay_platform?setUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
# 日志
logging:
  config: classpath:logback.xml

server:
  port: 9102
  servlet:
     session:
       timeout: 3600
# 分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  #开启驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  executor-type: simple

aliyun-oss:
  bucketName: wosz
  keyPrefix: mctpay/merchant/

email-properties:
  registChineseSubject: mctPay钱包注册